import Header from "./header"
import Input from "./Input"
import { SmallInp } from "./Input"
import InfoCard from "./InfoCard"
import Footer  from "./Footer"
import ProfileHeader from "./ProfileHeader"
import SideMenu from "./sideBar"
import SearchBox from "./Search"
import Loading from "./Loading"
export {Header, Input, SmallInp, InfoCard, Footer, ProfileHeader, SideMenu, SearchBox, Loading}
